### ISSUE TITLE
Creating Chains

### ISSUE THREAD

**Issue by StylingAndroid** [ConstraintLayout/constraintlayout.github.io#5]
Detail how we create chains both in XML and the editor

**Comment by AndrewScottWCU** [comment]
I still find this aspect of your documentation and the whole chaining thing weird and confusing. It would make much more sense if the visual editor, would actually create the chains in the code rather than using existing constraint attributes. It says to me the layout_constraintVertical_chainStyle and constraintHorizontal_chainStyle are essentially superfluous.  Am I correct on this observation?

**Comment by StylingAndroid** [comment]
This is an independent documentation page that is no longer actively updated. Please go to stackoverflow.com of you're looking for free technical help.
